# -*- coding: utf-8 -*-
"""Multi Class Animal Recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CXyI5lh21Ky3vP9JwgxwbNNMRIJqLhB8
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("iamsouravbanerjee/animal-image-dataset-90-different-animals")

print("Path to dataset files:", path)

#importing necessary library
import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import classification_report

#ensuring the gpu is used
physical_devices = tf.config.experimental.list_physical_devices('GPU')
if len(physical_devices) > 0:
    tf.config.experimental.set_memory_growth(physical_devices[0], True)
    print("gpu is being use")
else:
  print("gpu is not used")

import kagglehub
import os

# Download latest version
path = kagglehub.dataset_download("iamsouravbanerjee/animal-image-dataset-90-different-animals")

print("Path to dataset files:", path)

# Update dataset_path to the correct location using the downloaded path
dataset_path = os.path.join(path, "animals", "animals")  # Assuming the dataset is in 'animals/animals' within the downloaded path

#list all the class of animal types
classes = os.listdir(dataset_path)
num_classes = len(classes)

#display number of class and all names
print(f'Number of classes: {num_classes}')
print(f'Types of classes: {classes}')

# visualize some sample images from classes
i= 0
plt.figure(figsize = (35 , 30))
for i , class_name in enumerate(classes[:30]):
  class_path = os.path.join(dataset_path, class_name)
  img_name = os.listdir(class_path)[0]
  img_path = os.path.join(class_path, img_name)
  img = plt.imread(img_path)

  #  # Calculate the row and column indices for the subplot
  # row = i // 5  # Divide by number of columns to get row index
  # col = i % 3   # Use modulo to get column index

  plt.subplot(10, 3, i+1)
  plt.imshow(img)
  plt.title(f'{class_name} \n {img.shape}')
  plt.axis('off')
  plt.tight_layout()
plt.show()

#pre processing the data
#define the image size and batch_size-Trained model - MobileNetV2- 224*224

image_size = (224,224)
batch_size = 64 # there can be 64 imaeg in a batch

#data augementation and preprocesssing
datagen = ImageDataGenerator(
    rescale=1./255,        # we need to rescale this image to get its colour as colour range betn(0,255)
    validation_split = 0.1   # to check my model is performing good or not
)

#training and validation generator
train_generator = datagen.flow_from_directory(
    dataset_path,
    target_size = image_size,
    batch_size = batch_size,
    class_mode  = 'categorical',
    subset = 'training'
)
validation_generator = datagen.flow_from_directory(
    dataset_path,
    target_size = image_size,
    batch_size = batch_size,
    class_mode = 'categorical',
    subset = 'validation'
)

# map the classes - class_indices
class_indices = train_generator.class_indices
print(class_indices)

#extract the class manes
class_names = list(class_indices.keys())
print("class_names: ", class_names)

#Load MobileNetV2 as the base model
base_model = MobileNetV2(
    weights = 'imagenet',
    include_top = False,
    input_shape = (224,224,3)
)

#freeze the base model
base_model.trainable = False

#add custom layer on top of base model
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(1024,activation = 'relu')(x)
x = Dropout(0.5)(x)
predictions = Dense(num_classes, activation = 'softmax')(x) #output layer

#create the final model
model = Model(inputs = base_model.input, outputs = predictions)

#complie the model
model.compile(optimizer = Adam(learning_rate = 0.0001),
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])
#model summary
model.summary()

#train the model
history = model.fit(
    train_generator,
    steps_per_epoch =  train_generator.samples  //batch_size,
    validation_data = validation_generator,
    validation_steps = validation_generator.samples  //batch_size,
    epochs = 20
)

#evaluate the model - plotting the training and validation acc/loss
plt.figure(figsize = (12,6))

plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label = 'training accuracy')
plt.plot(history.history['val_accuracy'], label = 'validation accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label = 'training loss')
plt.plot(history.history['val_loss'], label = 'validation loss')
plt.title('Training and Validation loss')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

plt.show()

# eveluate of model on validation set (how well the model perform)
val_loss, val_accuracy = model.evaluate(validation_generator)
print(f'Validation Loss: {val_loss}')
print(f'Validation Accuracy: {val_accuracy}')

#save the model
model.save('MCAR.keras')

from google.colab import drive
drive.mount('/content/drive')

# how well it perform
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image

model = load_model('MCAR.keras')

def predict_animal(image_path):
  # Define target_size as a tuple
  target_size = (224, 224)
  img = image.load_img(image_path, target_size = target_size)  # Pass target_size as a keyword argument
  img_array = image.img_to_array(img)
  img_array = np.expand_dims(img_array, axis=0)
  img_array /= 255.0  # Corrected: Divide by 255.0 for normalization

  prediction = model.predict(img_array)
  predicted_class = class_names[np.argmax(prediction)]

  plt.imshow(img)
  plt.title(f'Predicted: {predicted_class}')
  plt.axis('off')
  plt.show()

os.listdir(os.path.join(path, "animals", "animals","parrot"))

predict_animal(os.path.join("/kaggle/input/animal-image-dataset-90-different-animals/animals/animals/","parrot",'34f9668c8e.jpg')) # updated

